//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LENS_FZ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LENS_FZ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DATA {
            get {
                object obj = ResourceManager.GetObject("DATA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Machine]
        ///Lines=AA057Z
        ///IDmachine=1
        ///ProjectName=M-39-01-00
        ///
        ///[SerialPort]
        ///SCanOption=True
        ///COM=COM6
        ///
        ///[setting]
        ///NET=true
        ///AccessPassword=6006
        ///AccessPath1=G:\LENS_FZ\LENS_FZ\bin\x86\Debug\DATA.mdb
        ///MysqlIP=192.168.200.11
        ///MysqlUsername=test
        ///MysqlPassword=123456788
        ///MysqlDatabaseName=MomenFZ
        ///MysqlTableName1=DataFZ
        ///MysqlPort=3306
        ///atimerInterval=5000
        ///Seventeen=1
        ///TablesNum=1
        ///OK=1
        ///NG=0
        ///
        ///[CD_FZ1]
        ///FZtype=MZ
        ///NextTime=2
        ///FZMax=1.28
        ///FzMin=0
        ///FZNum=1
        ///FZVideo=
        ///[CD_FZ2]
        ///FZtype=MF
        ///NextTime=2
        ///FZMax [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
    }
}
